import graficoCircular from "./modules/graficoCircular.js";
import graficoDeBarra from "./modules/graficoDeBarra.js";
import menuMobile from "./modules/menuMobile.js";
import sidebar from "./modules/sidebar.js";
import buttonMenu from "./modules/buttonConfig.js";
import loginBtn from "./modules/login.js";
import validateCadastro from "./modules/cadastro.js";
import logout from "./modules/logout.js";
import todoList from "./modules/listContas.js";
import user from "./modules/user.js";

graficoDeBarra();
graficoCircular();
menuMobile();
sidebar();
buttonMenu();
loginBtn();
validateCadastro();
logout();
todoList();
user();